<a href="https://colab.research.google.com/github/pavansai02/FreeCodeCamp-Pandas-Real-Life-Example/blob/master/fcc_pyrhon_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
 a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [5]:
b= np.array([[4,5,6],[7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [6]:
#Get dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Get shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#Get datatype
a.dtype

dtype('int64')

In [11]:
b.dtype

dtype('int64')

In [12]:
#Get Size
a.size

3

In [13]:
#Get total size
a.nbytes

24

In [15]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#Get a specific element [r,c]
a[1,3]

11

In [17]:
#Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [19]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [25]:
#Geeting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [27]:
#Changing a particular value in numpy array Eg-1
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
#Changing a particular value in numpy array Eg-2
a[:,2] = 5
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
#3D Array
b=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [32]:
#Accessing a specific element in 3D array
b[1,1,0]

6